export const FETCH_REGISTRATIONS_REQUEST = 'FETCH_REGISTRATIONS_REQUEST';
export const FETCH_REGISTRATIONS_SUCCESS = 'FETCH_REGISTRATIONS_SUCCESS';
export const FETCH_REGISTRATIONS_FAILED = 'FETCH_REGISTRATIONS_FAILED';
export const SET_REGISTRATIONS_PAGER = 'SET_REGISTRATIONS_PAGER';
  