export const FETCH_VISITIONS_REQUEST = 'FETCH_VISITIONS_REQUEST';
export const FETCH_VISITIONS_SUCCESS = 'FETCH_VISITIONS_SUCCESS';
export const FETCH_VISITIONS_FAILED = 'FETCH_VISITIONS_FAILED';

export const SET_VISITIONS_PAGER = 'SET_VISITIONS_PAGER';
  